language: android
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - tools
    - platform-tools

    # The BuildTools version used by your project
    - build-tools-28.0.3

    # The SDK version used to compile your project
    - android-28

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - extra
    - add-on

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    #- sys-img-x86-android-25
    #- sys-img-armeabi-v7a-android-25
    - sys-img-armeabi-v7a-google_apis-25
  
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_install:
  - yes | sdkmanager "platforms;android-25;sys-img-armeabi-v7a-google_apis-25"
  - echo y | android update sdk --no-ui --all --filter sys-img-armeabi-v7a-google_apis-25

env:
  global:
   # install timeout in minutes (2 minutes by default)
    - ADB_INSTALL_TIMEOUT=8

# Emulator Management: Create, Start and Wait
before_script:
  - android list targets
  - android list sdk --extended --no-ui --all
  - echo no | android create avd --force -n test -t android-25 --abi google_apis/armeabi-v7a --skin 480x800
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
   - ./gradlew clean lint build connectedCheck

